#!/bin/bash
#while read server; do
echo -e "|**********************************************|"
echo "     Start time - `date`"
echo -e "|**********************************************|"
echo ""
start_time=$(date +%s)

#SUCESS = able to login in to the server without password
#FAIL   = server is either not passwordless from that host youre logged into or can have any other issue such as server is down \ ssh is using different port than 22 \ ssh service is having an issue etc...
echo -e "|****************************************************************************************************|"
echo -e "            \033[5m\033[4mScript is testing passwordless access from the local host you running it from\033[0m"
echo -e "|****************************************************************************************************|"

echo ""

for server in `cat servers`;do

        timeout 20 ssh -o "BatchMode yes" -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey $server "echo -n" &>/dev/null

  if [ $? -eq 0 ]; then
        echo -e "$server \033[1;32m* SUCCESS *\033[0m"

else
        echo -e "$server \033[1;31m* FAIL *\033[0m"
  fi

done | tee /tmp/sshtest
echo ""
echo ""
echo -e "\033[1;32m* SUCCESS *\033[0m = \033[5m\033[4mable to login into the server without using a password\033[0m"
echo -e "\033[1;31m* FAIL *\033[0m   = \033[5m\033[4mserver is either not passwordless from that host youre logged into or can have any other issue such as server is down \ ssh is using different port than 22 \ ssh service is having an issue etc...\033[0m"

echo -e "|**********************************************|"
echo "     End time - `date`"
echo -e "|**********************************************|"
echo ""
end_time=$(date +%s)
total_time=$((end_time - start_time))
echo "|      Total running time: $total_time seconds    |"

echo ""
echo ""
echo "          |************************************************************|"
echo "          |                                                            |"
echo -e "          |                 \033[5m\033[4mLog File - /tmp/sshtest\033[0m                    |"
echo "          |                                                            |"
echo "          |************************************************************|"

